name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: pip install mkdocs-literate-nav
      - run: pip install mkdocs-git-authors-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install lightgallery
      - run: mkdocs gh-deploy --force
